// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkzdjncthsrlobkfadio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhremRqbmN0aHNybG9ia2ZhZGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjM5MjMsImV4cCI6MjA3MTA5OTkyM30.tw-TwdhiXON-Dt4pRUJcg4Hrj_uNt6fCT2NAM9Y_zHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});