// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqzmgrydmigwgbshnlxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxem1ncnlkbWlnd2dic2hubHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDI2NjIsImV4cCI6MjA3MTExODY2Mn0.1AmVKZyBNd_Gpyl3Dyjhdlr3Imsb_4wvwNQH8a3fT_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});